# Configuration file for TravisCI

# We use miniconda for Python so don't need any Python specific tools
language: generic

sudo: false

env:
  global:
    - MASTER_BRANCH=master
    - PYPI_PY=3.7  # deploy to pypi from python 3.6
    - GAE_PROJECT=discretize  # name of the google app engine project
    - TEST=false
    - TEST_DIR=""
    - DEPLOY_DOCS=false
    - DEPLOY_PYPI=false
    - CONDA_REQUIREMENTS="numpy scipy matplotlib cython pip"
    - PYPI_REQUIREMENTS=requirements.txt
    - PYPI_REQUIREMENTS_DEV=requirements_dev.txt

matrix:
  include:
    # test the base code on 2.7, 3.6, 3.7
    - name: "Python 2.7 - base"
      os: linux
      env:
        - PYTHON=2.7
        - TEST=true
        - TEST_DIR="tests/base"
    - name: "Python 3.6 - base"
      os: linux
      env:
        - PYTHON=3.6
        - TEST=true
        - TEST_DIR="tests/base"
    - name: "Python 3.7 - base"
      os: linux
      env:
        - PYTHON=3.7
        - TEST=true
        - TEST_DIR="tests/base"

    # test the cyl code on 2.7, 3.6, 3.7
    - name: "Python 2.7 - cyl"
      os: linux
      env:
        - PYTHON=2.7
        - TEST=true
        - TEST_DIR="tests/cyl"
    - name: "Python 3.6 - cyl"
      os: linux
      env:
        - PYTHON=3.6
        - TEST=true
        - TEST_DIR="tests/cyl"
    - name: "Python 3.7 - cyl"
      os: linux
      env:
        - PYTHON=3.7
        - TEST=true
        - TEST_DIR="tests/cyl"

    # test the cyl code on 2.7, 3.6, 3.7
    - name: "Python 2.7 - tree"
      os: linux
      env:
        - PYTHON=2.7
        - TEST=true
        - TEST_DIR="tests/tree"
        - DEPLOY_PYPI=true
        - CONDA_INSTALL_EXTRA="twine"
    - name: "Python 3.6 - tree"
      os: linux
      env:
        - PYTHON=3.6
        - TEST=true
        - TEST_DIR="tests/tree"
        - DEPLOY_PYPI=true
        - CONDA_INSTALL_EXTRA="twine"
    - name: "Python 3.7 - tree"
      os: linux
      env:
        - PYTHON=3.7
        - TEST=true
        - TEST_DIR="tests/tree"
        - DEPLOY_PYPI=true
        - CONDA_INSTALL_EXTRA="twine"

    # test the docs code on 3.6, 3.7
    - name: "Python 3.6 - docs"
      os: linux
      env:
        - PYTHON=3.6
        - TEST=true
        - TEST_DIR="tests/docs"
    - name: "Python 3.7 - docs"
      os: linux
      env:
        - PYTHON=3.7
        - TEST=true
        - TEST_DIR="tests/docs"
        - DEPLOY_DOCS=true

before_install:
  - source ci/setup-miniconda.sh
  - conda list

install:
  - pip install -e .
  - make build

script:
  - if [ "$TEST" == "true" ]; then
      export MPLBACKEND="agg" ;
      echo "testing $TEST_DIR" ;
      pytest $TEST_DIR --cov-config .coveragerc --cov=discretize -v -s ;
    fi

after_success:
  - if [ "$TEST" == "true" ]; then
      echo "Uploading coverage to Codecov";
      codecov;
    fi

deploy:
  # pypi release
  - provider: script
    script: ci/deploy-pypi.sh
    skip_cleanup: true
    on:
      tags: true
      condition: '$DEPLOY_PYPI == "true"'
  # deploy docs
  - provider: script
    script:
      if [ ! -d "credentials" ]; then
          openssl aes-256-cbc -K $encrypted_5813a1339455_key -iv $encrypted_5813a1339455_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
          tar -xzf credentials.tar.gz
      fi

      # add conda to path
      export PATH="$HOME/miniconda/bin:$PATH"

      # authenticate with gcloud
      cd docs
      echo "Starting deploy of the docs"

      # install and setup lib
      conda create -n py27 python=2.7
      conda activate py27
      mkdir lib
      pip install -t lib/ flask
      ls lib
      conda deactivate
      curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-228.0.0-linux-x86_64.tar.gz
      tar zxvf google-cloud-sdk
      pip install google-compute-engine

      # deploy
      gcloud auth activate-service-account --key-file credentials/client-secret.json
      echo "Successfully authenticated"
      gcloud config set project $GAE_PROJECT
      gcloud app deploy app.yaml --version ${TRAVIS_COMMIT} --promote
      echo "Done deploying docs"

    skip_cleanup: true
    on:
      condition: '$DEPLOY_DOCS == "true"'
      # branch: master

notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n
  email: false
