language: python
python:
- 2.7
- 3.5
- 3.6
matrix:
  allow_failures:
    - python: 3.6

secure: "oaDh/n+3yFeb6n2JN8ps1EQGu5WynsabaIDIVABuQu5mFKy8kXsS3aZBtnLOBA/Ws8hwgACxLT0zbPXA651hdi9HgO8UxjK8xDWcI3lyZu/LFu2CQn+q5Mx27XgDoT6HjNrCMDdS4G7/2cqFvY1Hf8w78TU2aRa1nOntMWbDM8ltS5LnP1kc9epFUzkiqYAvGFb0xwSrTDWa8IF0IIXA0i4RDn80Llf9RR2YcayqZ6oWMDNosGZr9LVATwsAqrSNCzbZ7flX4WPrN0DtfmDsRx8N3DWjYpzRKQdoJErrfQBPLO13QFGyaCY33OKgK2+nzFde6cl8qeWAEZkV81d0UvvPH9AKN0LHhsWGdDBdv7mFfmdQMGQtq1jgBupFMmEFXfwTGvisSgkTWB87oJd4gYuNnmgVWoWHmD1n02LhnlyaCpt0nHGMT/RPsZ0kttkHpx7abuqmBBv5hRdsCAxhqJ7718WlF8PIfHhbRWWr4XHQLxORHfYsywonR+PCP3s5sqN6SHIbkZxe44PDuoNsm9v84/dJcSkEOh97THpBuWsSoAWMbg445kbudEhiN457XE3FGRJj7B6Kv2KE4xJURNMlfqiOBvZcloS6Vxzbdh8O5plcOaJmz662fxHRWw6RXZoihzHS2Wco7lPJlNEDE+/k6h8/dD64a88uyptaJHw="

sudo: false

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pillow cython ipython vtk;
    else
      conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pillow cython ipython;
    fi
  - pip install -r requirements_dev.txt
  - python setup.py install
  - make build

script:
  - nosetests tests/base tests/tree tests/docs --with-cov --cov discretize --cov-config .coveragerc -v -s;

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n
