# AppVeyor.com is a Continuous Integration service to build and run tests under Windows

build:
  verbosity: normal

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    # - PYTHON_VERSION: 3.5
    #   MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy matplotlib cython ipython"
  - activate test-environment
  - pip install -r requirements_dev.txt
  - "%PYTHON%\\python.exe setup.py install"
  - "%PYTHON%\\python.exe setup.py build_ext -i -b ."

test_script:
  - nosetests
