name: discretize-docs

channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - cython>=0.2
  - matplotlib>=1.3
  - numpy>=1.8
  - pillow
  - scipy>=0.13
  - sphinx
  - sympy
  - pip:
    - nbsphinx
    - numpydoc
    - properties[math]
    - pymatsolver>=0.1.2
    - sphinx_rtd_theme
    - sphinx-gallery
    - vtk
    - vtki>=0.16.9
