name: discretize-docs

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cython
  - matplotlib
  - numpy
  - pillow
  - scipy
  - sphinx
  - sympy
  - pip:
    - nbsphinx
    - numpydoc
    - properties[math]
    - pymatsolver
    - sphinx_rtd_theme
    - sphinx-gallery
    - vtk
    - vtki
